### ISSUE TITLE
Finding correct python interpreter on Windows with conda

### ISSUE THREAD

**Issue by mducle** [brille/brille#47]
Brille uses two CMake packages to determine the correct Python interpreter to compile the C++ extension module for:

* [FindPython3](https://cmake.org/cmake/help/latest/module/FindPython3.html) by default
* [FindPythonInterp](https://cmake.org/cmake/help/latest/module/FindPythonInterp.html) which is called by [pybind11](https://github.com/pybind/pybind11/blob/master/tools/FindPythonLibsNew.cmake#L98)

FindPython3 is more robust / newer / better so it is used to override FindPythonInterp. However, this [overriding code](https://github.com/brille/brille/blob/master/CMakeLists.txt#L86) also means that if the flag `PYTHON_EXECUTABLE` is set (by [`setup.py`](https://github.com/brille/brille/blob/master/setup.py#L72)) this is ignored. 

On a Linux conda environment, FindPython3 respects the `PATH` environment and returns the correct interpreter for a given conda environment. On Windows, however, FindPython3 seems to always return the main _system_ Python interpreter instead of the one for a specific environment. This means running `python setup.py install` or `pip install .` in a conda environment on Windows produces the wrong extension module.

A possible fix might be:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index df10291..1d16532 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -86,7 +86,7 @@ set(CMAKE_POSITION_INDEPENDENT_CODE ON)
 find_package(Python3 COMPONENTS Interpreter Development)
 # Since FindPython3 and FindPythonInterp set different variables, fake the FindPythonInterp result
 # to prevent it running if called by, e.g., FindPybind11
-if(Python3_FOUND)
+if(Python3_FOUND AND NOT PYTHON_EXECUTABLE)
   set(PYTHONINTERP_FOUND ON)
   set(PYTHON_EXECUTABLE ${Python3_EXECUTABLE})
   set(PYTHON_VERSION_STRING "${Python3_VERSION}")
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 5ca25ac..d28d333 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -14,6 +14,7 @@ endif()
 #   )
 # endif()

+message(STATUS "Using interpreter: ${PYTHON_EXECUTABLE}")

 set(CXX_SOURCES
   bravais.cpp
```

This would ensure that the `PYTHON_EXECUTABLE` flag is respected if it is passed to cmake, and if not then FindPython3 is used.

**Comment by g5t** [comment]
The applied solution still has problems in some cases, and is related to a [pybind11 FAQ entry](https://github.com/pybind/pybind11/blob/0fb981b21966339b811bc770b11f71eddd918f13/docs/faq.rst#inconsistent-detection-of-python-version-in-cmake-and-pybind11).
Enforcing a newer version of `CMake` and implementing `solution 2.` from the linked FAQ seems to fix the problem.
A user can still specify which Python interpreter should be used, since `find_package(Python COMPONENTS Interpreter Development)` can be forced to use a specific interpreter if `Python3_EXECUTABLE` is defined beforehand.
