### ISSUE TITLE
Attempting to access null node with La2Zr2O7

### ISSUE THREAD

**Issue by rebeccafair** [brille/brille#64]
_Originally reported by @ajjackson in https://github.com/pace-neutrons/Euphonic/issues/104#issuecomment-1040116096_

When trying to interpolate at a specific q-point with La2Zr2O7 the following error is raised:
```
The node subscript  6 6 0 for the point [[ 0.0903,  0.1026,  0.0147]] is either invalid or points to a null node!
Traceback (most recent call last):
  File "brille_bug_lzo.py", line 38, in <module>
    grid.ir_interpolate_at(qpts)
RuntimeError: attempting to access null node!
```

This can be replicated using the following script:
```
import spglib as spg
import numpy as np
from euphonic import ForceConstants

import brille as br

# Get crystal data
fc = ForceConstants.from_json_file('LZO_force_constants.json')
crystal = fc.crystal
cell_vectors = crystal._cell_vectors
cell = crystal.to_spglib_cell()

# Create grid from crystal
dataset = spg.get_symmetry_dataset(cell)
rotations = dataset['rotations']  # in fractional
translations = dataset['translations']  # in fractional
symmetry = br.Symmetry(rotations, translations)
direct = br.Direct(*cell)
direct.spacegroup = symmetry
bz = br.BrillouinZone(direct.star)
vol = bz.ir_polyhedron.volume

# This grid causes RuntimeError: attempting to access null node!
grid = br.BZTrellisQdc(bz, node_volume_fraction=vol/5000)

# This grid quietly causes a segfault
#grid = br.BZNestQdc(bz, number_density=1000)

# Fill grid with whatever
n_atoms = crystal.n_atoms
values = np.ones((len(grid.rlu), 3*n_atoms, 1), dtype=np.float64)
vectors = np.ones((len(grid.rlu), 3*n_atoms, 3*n_atoms), dtype=np.complex128)
grid.fill(values, (1,), (1., 0., 0.),
          vectors, (0., 3*n_atoms, 0, 3, 0, 0), (0., 1., 0.))

# Cause error
qpts = np.array([[-0.13362825, -0.01771817, -0.11614479]])
grid.ir_interpolate_at(qpts)
```

The Euphonic force constants file used in the script can be found [here](https://github.com/pace-neutrons/Euphonic/blob/master/tests_and_analysis/test/data/force_constants/LZO_force_constants.json).

This happens with Brille 0.5.7. on both Windows and Linux. This only seems to happen with `BZTrellisQdc` specifically with the arguments used above. Also while doing this I found that using `BZNestQdc` with that q-point and `number_density=1000` causes a silent segfault. Maybe that requires a separate issue...

**Comment by rebeccafair** [comment]
Another data point:
Using `qpts = np.array([[-0.14197496,  0.491958  , -0.36618576]])` I get
```
The node subscript  23 18  7 for the point [[ 0.3436,  0.2824,  0.1176]] is either invalid or points to a null node!
Traceback (most recent call last):
  File "brille_bug_lzo.py", line 43, in <module>
    grid.ir_interpolate_at(qpts)
RuntimeError: attempting to access null node!
```

**Comment by g5t** [comment]
This issue is quite insiduous. There is a bug somewhere in `v0.5.7` which I _hope_ has not been present since `v0.0.1`. Somehow `brille==v0.5.7` is not finding the correct first or irreducible Brillouin zone for La<sub>2</sub>Zr<sub>2</sub>O<sub>7</sub>, nor is it constructing a valid polyhedron-filling grid. All of these points are visible by using `brille.plotting.plot` to display the generated grid object:
![lzo_grid_v0 5 7](https://user-images.githubusercontent.com/5982344/161746636-1c8f11fa-ecc9-406c-81d6-bf1fac5bcb68.png)
The dashed lines should be the edges of a Face Centered first Brillouin zone (compare to [an image search result](https://www.google.com/search?q=face+centred+brillouin+zone)); and the blue dots are vertices of the generated `brille.BZTrellisQdc` grid which should all be inside the 'irreducible Brillouin zone' polyhedron (not visible).

Finding the cause of this failure would likely require a triage of some sort, maybe via [`git bisect`](https://git-scm.com/docs/git-bisect), but this has not been attempted yet. Instead, the internal handling of floating-point comparisons, polyhedra, and lattices, have been modified in an attempt to make the construction of a Brillouin zone and polyhedron-filling grid more robust.
As mentioned in #63 this led to necessary API changes in a [v0.6.0 development branch](https://github.com/brille/brille/tree/64_polyhedra).

`brille.Lattice` replaces `brille.Direct` and `brille.Reciprocal` and, importantly, holds internally the basis-vector matrices and lattice metrics for both the real space and reciprocal space lattices, instead of only the basis-vector lengths and inter-basis-vector angles. The [basis vectors](https://github.com/pace-neutrons/Euphonic/blob/aa3cc28786797bb3052f898dd63d4928d6f27ee2/tests_and_analysis/test/data/force_constants/LZO_force_constants.json#L186) contained in `LZO_force_constants.json`  are those of the primitive lattice and, as such, should all have the same length and be 60° apart, instead their lengths and angles are `( 7.5839128243499987 7.5839128243445124 7.5839128243445124)Å` `( 59.9999999999612257 60.0000000000193836 60.0000000000193836)°`, which is too-far-off for the default `brille==v0.6.0` floating point tolerance comparisons to successfully find a first Brillouin zone.
A modified version of your script which works with development `v0.6.0` is:

```python
import spglib as spg
import numpy as np
from euphonic import ForceConstants

import brille as br
print(f"Using brille version {br.version} built {br.build_datetime} or {br.build_hostname}")
ac = br.ApproxConfig()
ac.reciprocal_space_tolerance = 2e-12

# Get crystal data
euphonic_root = 'path_to_your_euphonic_repository'
filename=f"{euphonic_root}/tests_and_analysis/test/data/force_constants/LZO_force_constants.json"
fc = ForceConstants.from_json_file(filename)
crystal = fc.crystal
cell_vectors = crystal._cell_vectors
basis_vectors, atom_positions, atom_types = crystal.to_spglib_cell()

# Create grid from crystal
dataset = spg.get_symmetry_dataset((basis_vectors, atom_positions, atom_types))
rotations = dataset['rotations']  # in fractional
translations = dataset['translations']  # in fractional
symmetry = br.Symmetry(rotations, translations)
basis = br.Basis(atom_positions, atom_types)
lattice = br.Lattice(basis_vectors, symmetry, basis)
bz = br.BrillouinZone(lattice, ac)
vol = bz.ir_polyhedron.volume

# This grid causes RuntimeError: attempting to access null node!
grid = br.BZTrellisQdc(bz, node_volume_fraction=vol/5000)

# This grid [does not appear to] quietly cause a segfault [any longer]
#grid = br.BZNestQdc(bz, number_density=1000)

# Fill grid with whatever
n_atoms = crystal.n_atoms
values = np.ones((len(grid.rlu), 3*n_atoms, 1), dtype=np.float64)
vectors = np.ones((len(grid.rlu), 3*n_atoms, 3*n_atoms), dtype=np.complex128)
grid.fill(values, (1,), (1., 0., 0.),
          vectors, (0., 3*n_atoms, 0, 3, 0, 0), (0., 1., 0.))

# [Don't] Cause error
qpts = np.array([[-0.13362825, -0.01771817, -0.11614479],
                 [-0.14197496,  0.491958,   -0.36618576]])
grid.ir_interpolate_at(qpts)
```
And, again `brille.plotting.plot` can give us confidence that the correct first Brillouin zone, a valid irreducible Brillouin zone, and the a correct polyhedron-filling grid have been created:
![lzo_grid_v0 6 0](https://user-images.githubusercontent.com/5982344/161750513-bd528172-ab6e-4f5e-bd84-0e2db94a9682.png)

**Comment by rebeccafair** [comment]
Can confirm that this error no longer arises in version `0.6.0+64_polyhedra.8a5e72b` if I use the script you just posted, so this issue can be closed. It originally wasn't working for me and was silently segfaulting, but my problem was I wasn't adding the basis to the lattice! Maybe I was just being dumb and it was obvious that I needed to do that, but it would be good to have some more docs (or a useful error?).

I have found a new issue in this version though, see https://github.com/brille/brille/issues/67
