### ISSUE TITLE
Null node with LZO and Trellis

### ISSUE THREAD

**Issue by rebeccafair** [brille/brille#85]
This was found on Windows and Python 3.8 running `euphonic-brille-convergence.exe castep_files\La2Zr2O7.castep_bin --brille-grid trellis --brille-npts 10000` from https://github.com/pace-neutrons/Euphonic/pull/104/commits/2b9c82497ff9684370449a7069b9c76c89abfe8c

I have created a `BZTrellisQdc` object for [LZO](https://github.com/pace-neutrons/Euphonic/blob/master/tests_and_analysis/test/data/castep_files/LZO/La2Zr2O7.cell) using `node_volume_fraction=1.6754573184766842e-06` and `always_triangulate=False` (link to hdf5 of filled grid [here](https://www.dropbox.com/s/ed0fean2aa1xv8z/lzo_trellis_filled.hdf5?dl=0), beware its ~1GB) and if I run the following script:

```
import numpy as np
from brille import BZTrellisQdc

lzo_grid = BZTrellisQdc.from_file('lzo_trellis_filled.hdf5')
qpts = np.array([[0.71056334, 0.87427782, 0.70768662]])
vals, vecs = lzo_grid.ir_interpolate_at(qpts)
```
I get the error:
```
The node subscript  20, 11,  6, for the point (hkl) [[ 0.2421783025262824,  0.1356355800935403,  0.0719665443032025]](xyz)   0.2421783025262824,  0.1356355800935403,  0.0719665443032025, is either invalid or points to a null node!
```
`brille.version` gives `0.6.1.dev16+g7698bb6`

**Comment by rebeccafair** [comment]
Script to reproduce grid:
```
import spglib as spg
import numpy as np
from euphonic import ForceConstants

import brille as br
from brille import BZTrellisQdc

fc = ForceConstants.from_castep('castep_files\La2Zr2O7.castep_bin')
crystal = fc.crystal
cell_vectors = crystal._cell_vectors
cell = crystal.to_spglib_cell()

dataset = spg.get_symmetry_dataset(cell)
rotations = dataset['rotations']  # in fractional
translations = dataset['translations']  # in fractional

symmetry = br.Symmetry(rotations, translations)
basis = br.Basis(cell[1], cell[2])
lattice = br.Lattice(cell[0], symmetry=symmetry, basis=basis,
                     snap_to_symmetry=True)

ac = br.ApproxConfig()
ac.reciprocal_space_tolerance = 1e-8
bz = br.BrillouinZone(lattice)

vol = bz.ir_polyhedron.volume
lzo_grid = BZTrellisQdc(bz, node_volume_fraction=vol/1e4, always_triangulate=False, approx_config=ac)
# frequencies, freq_el, freq_weight, evecs, evecs_el, evecs_weight
nqpts = len(lzo_grid.rlu)
n_atoms = crystal.n_atoms
lzo_grid.fill(np.ones((nqpts, 3*n_atoms, 1)), (1,), (1., 0., 0.),
              np.ones((nqpts, 3*n_atoms, 3*n_atoms), dtype=np.complex128),
              (0, 3*n_atoms, 0, 3, 0, 0), (0., 1., 0.))

# Alternatively read grid from file
#lzo_grid = BZTrellisQdc.from_file('lzo_trellis_filled.hdf5')

qpts = np.array([[0.71056334, 0.87427782, 0.70768662]])
vals, vecs = lzo_grid.ir_interpolate_at(qpts)
```

**Comment by g5t** [comment]
The intersection algorithm uses approximate floating point equivalence checks for more than just the volume, and changing the tolerance for *just* the volume check to `s_tol * s_tol * s_tol` is insufficient for this case. On the other hand, while changing the specified tolerance as indicated above works for this case, it breaks other test cases since the resulting polygon has 'too precise' vertices compared to the precision used in the rest of the `PolyTrellis` constructor.

The volume check is used only to short-cut the intersection algorithm and can be omitted entirely. Within the intersection algorithm there are then two places where the tolerance is used:
1. The first compares already-known vertices to the intersection point of each edge of one polyhedron and a single plane of the second. If the intersection point is new it is added to the facet index lists for each face containing the edge as well as a newly formed face.
2. The second compares successive edges on one face for colinearity and removes the central vertex index for any found-colinear edge pairs.

It is this second case where the too-large tolerance seems to be most important. 
The current colinear check compares the cross product of the directed edge vectors with zero. If the edge lengths are small or the edges are nearly colinear their cross product approaches zero.
Removing the edge length aspect of the check by normalising each vector before taking the cross product fixes this problem but again breaks other tests.

A better colinearity check or a separate check against too-short edge lengths may resolve this issue without breaking existing tests.

**Comment by g5t** [comment]
I've chosen to follow solution `1a` above. 

Strangely, the second test which failed previously (by throwing the wrong error type) now passes on `macOS` systems!
This problem is solved by adding the `[!mayfail]` tag to the `TEST_CASE` and, with possibly little utility, the `[!nonportable]` tag as well as reminder.
