### ISSUE TITLE
Bug (?) Wrong irreducible brillouin zone (IBZ)

### ISSUE THREAD

**Issue by SiyuChen** [brille/brille#96]
```
import brille

direct_lattice = brille.Direct((5.728, 3.174, 20.0), (90, 90, 90), 'P2_1/m')
brillouin_zone = brille.BrillouinZone(direct_lattice.star, time_reversal_symmetry=True)

print(brillouin_zone.ir_vertices)
```
output:
[[-5.00000000e-01  5.00000000e-01  5.00000000e-01]
 [ 5.00000000e-01  5.00000000e-01  5.00000000e-01]
 [-5.00000000e-01  5.00000000e-01 -2.65046223e-16]
 [ 5.00000000e-01  5.00000000e-01  2.65046223e-16]
 [-5.00000000e-01 -2.31831043e-17  5.00000000e-01]
 [ 5.00000000e-01  3.29006766e-17  5.00000000e-01]
 [-5.00000000e-01 -2.80418904e-17 -2.65046223e-16]
 [ 5.00000000e-01  2.80418904e-17  2.65046223e-16]]

This result does not make sense to me. Should it be:
[[**0.0**  5.00000000e-01  5.00000000e-01]
 [ 5.00000000e-01  5.00000000e-01  5.00000000e-01]
 [**0.0**  5.00000000e-01 -2.65046223e-16]
 [ 5.00000000e-01  5.00000000e-01  2.65046223e-16]
 [**0.0** -2.31831043e-17  5.00000000e-01]
 [ 5.00000000e-01  3.29006766e-17  5.00000000e-01]
 [**0.0** -2.80418904e-17 -2.65046223e-16]
 [ 5.00000000e-01  2.80418904e-17  2.65046223e-16]] ?

See Fig.7 in https://arxiv.org/pdf/1004.2974.pdf

**Comment by g5t** [comment]
Thanks for trying out `brille`, I hope we can get to the bottom of this together.

## Possible errors
I see a few points where `brille` could be doing something wrong, or at least something unexpected. Can you help me decide which (if any) is a likely culprit?
1. `brille` uses Hall symbols (or, alternatively, explicit symmetry operations) but you've provided a spacegroup's Hermann-Mauguin symbol. `brille` contains a table with relationships between HM and Hall symbols, which could be erroneous. The lines for  `'P2_1/m'` are https://github.com/brille/brille/blob/310f968ee506ce134e806a0ed32e2da9c8469039/src/spg_database.cpp#L139-L141 which indicates that it has three axes choices, with Hall symbols `-P 2yb`, `-P 2c` and `-P 2xa`. Is this relationship between spacegroup representations correct?
2. All three Hall groups are comprised of four symmetry operations, including space inversion. Is this what you expect for `P2_1/m`?
3. Adding the time reversal symmetry flag has no effect in `brille` since the spacegroup already includes space inversion. A future change might handle, e.g., magnetic spacegroups directly which will necessitate treating time-reversal differently. Did you expect adding this flag to have a different effect?

## Alternatives
If none of those are the cause of this issue, then I think `brille` is providing a correct answer. I'm using the latest development version with `brille.version == '0.7.1.dev27+g142b36d'`, which has a slightly different API and handles rounding a bit better; but gives the same result. 

With four operations in the pointgroup, we should expect the Brillouin zone to occupy one-quarter of the Wigner-Seitz cell. If this isn't obvious from the reported vertex positions, we can apply each pointgroup operation to the polyhedron and then overplot them to check that they tile space.
![brille96_p21m_irbzs](https://github.com/brille/brille/assets/5982344/d5e32543-0cc6-4735-a076-a6c3e66dd8b3)

### The modified script
```python
import brille

lattice = brille.Lattice(((5.728, 3.174, 20.0), (90, 90, 90)), 'P2_1/m')
brillouin_zone = brille.BrillouinZone(lattice, time_reversal_symmetry=True)

print(brillouin_zone.ir_vertices)

p21m_s = lattice.spacegroup
p21m_ps = brille.PointSymmetry(p21m_s)
polys = [brillouin_zone.ir_polyhedron.rotate(p21m_ps, index) for index in range(p21m_ps.size)]


import brille.plotting as bp
import matplotlib.pyplot as pp

ax = bp.plot_polyhedron(polys[0], show=False)
[bp.plot_polyhedron(polys[x], show=False, axs=ax) for x in range(1, len(polys))]
pp.setp(ax, 'xlim',[-0.5, 0.5], 'ylim', [-0.5, 0.5], 'zlim', [-0.5, 0.5])
pp.setp(ax, 'xlabel', 'a*', 'ylabel', 'b*', 'zlabel', 'c*')
pp.show()
```
